doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\mysqlPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'App\Shared\Infrastructure\Persistence\Doctrine\Entity'
                alias: App
            ShippingCostCalculator:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/ShippingCostCalculator/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'App\ShippingCostCalculator\Infrastructure\Persistence\Doctrine\Entity'
                alias: ShippingCostCalculator
            Connectif:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Connectif/Infrastructure/Persistence/Doctrine/Model'
                prefix: 'App\Connectif\Infrastructure\Persistence\Doctrine\Model'
                alias: Connectif
            Priceshape:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Priceshape/Infrastructure/Persistence/Doctrine/Model'
                prefix: 'App\Priceshape\Infrastructure\Persistence\Doctrine\Model'
                alias: Priceshape

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
