security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        users_in_memory: { memory: null }

        feed_provider:
            memory:
                users:
                    priceshape: { password: '$2y$13$HCS5IVaUBa9XbUSW7aMBuuQRLWgVaZzXIYPV1Uznk/m3GL9aFz2fu', roles: [ROLE_FEED_CONSUMER]}

        warehouse_provider:
            memory:
                users:
                    kompy: { password: '$2y$13$6zwxFD9ehYHGis1LxTZ96evuTLsjjAr5eZb.BE9oWxyRHz/Y3gEk6', roles: [ ROLE_WAREHOUSE ] }

        cron_provider:
            memory:
                users:
                    cronjob: { roles: [ROLE_CRONJOB] }

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        ops_feeds:
            host: ^ops\.kompymascotas\.com$
            pattern: ^/feed/
            provider: feed_provider
            http_basic:
                realm: "Acceso protegido"

        warehouse:
            host: ^warehouse\.kompymascotas\.com$
            provider: warehouse_provider
            http_basic:
                realm: "Acceso protegido"

        ops:
            host: ^ops\.kompymascotas\.com$
            stateless: true
            provider: cron_provider
            access_token:
                token_handler: App\Shared\Security\AccessTokenHandler

        main:
            lazy: true
            provider: users_in_memory
            # Activate different ways to authenticate:
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Note: Only the *first* matching rule is applied
    access_control:
        - { host: ^ops\.kompymascotas\.com$, path: ^/feed/, roles: ROLE_FEED_CONSUMER }
        - { host: ^ops\.kompymascotas\.com$, roles: ROLE_CRONJOB }
        - { host: ^warehouse\.kompymascotas\.com$, roles: ROLE_WAREHOUSE}
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
