# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
services:
    # para poder probarlo hay que declararlo público o como no se usa en ningún servicio en la prueba el container lo eliminará
    # Hace que el servicio sea accesible vía $container->get() solo en tests
    App\ShippingCostCalculator\Service\Calculator:
        public: true

    App\ShippingCostCalculator\Infraestructure\Repository\RangeRepository:
        public: true
