# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    kpy.base_domain: '%env(BASE_DOMAIN)%'

    kpy.google_dir: '%kernel.project_dir%/var/google'

    kpy.feeds_dir: '%kernel.project_dir%/var/feeds'

    connectif.log_dir: '%kernel.logs_dir%/connectif'

    kpy.priceshape.var_dir: '%kpy.feeds_dir%/priceshape'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $aquaDSN: '%env(AQUA_DSN)%'
            $aquaUser: '%env(AQUA_USER)%'
            $aquaPassword: '%env(AQUA_PASSWORD)%'

            $kompyDbUser: '%env(KOMPY_DB_USER)%'
            $kompyDbPassword: '%env(KOMPY_DB_PASSWORD)%'
            $kompyDSN: '%env(KOMPY_DB_DSN)%'
            $kompyDbPrefix: '%env(KOMPY_DB_PREFIX)%'

            $doctrineDSN: '%env(DOCTRINE_DSN)%'
            $doctrineUser: '%env(DOCTRINE_USER)%'
            $doctrinePassword: '%env(DOCTRINE_PASSWORD)%'

            $pymLegacyDSN: '%env(PYM_LEGACY_DB_DSN)%'
            $pymLegacyUser: '%env(PYM_LEGACY_DB_USER)%'
            $pymLegacyDbPrefix: '%env(PYM_LEGACY_DB_PREFIX)%'
            $pymLegacyPassword: '%env(PYM_LEGACY_DB_PASSWORD)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    _instanceof:
        App\Shared\Infrastructure\Database\Factory\DatabaseFactoryInterface:
            tags: ['kpy.database_factory']

    # si queremos inyectar una instancia de Database para Aqua, Symfony usara el factory para crear la instancia
    aquaDatabaseRoot:
        class: App\Shared\Infrastructure\Database\Database
        factory: [ '@App\Shared\Infrastructure\Database\Factory\DatabaseAquaFactory', 'create' ]

    aquaDatabase:
        class: App\Shared\Infrastructure\Database\Decorator\DatabaseLoggerDecorator
        arguments:
            $database: '@aquaDatabaseRoot'
            $databaseName: '%env(AQUA_DATABASE)%'
            $type: !php/const App\Shared\Infrastructure\Database\DatabaseType::SQLServer


    kompyDatabaseRoot:
        class: App\Shared\Infrastructure\Database\Database
        factory: ['@App\Shared\Infrastructure\Database\Factory\DatabaseKompyFactory', 'create']

    kompyDatabaseLogger:
        class: App\Shared\Infrastructure\Database\Decorator\DatabaseLoggerDecorator
        arguments:
            $database: '@kompyDatabaseRoot'
            $databaseName: '%env(KOMPY_DB_NAME)%'
            $type: !php/const App\Shared\Infrastructure\Database\DatabaseType::MySQL

    kompyDatabase:
        class: App\Shared\Infrastructure\Database\Decorator\DatabasePrefixerDecorator
        arguments:
            $database: '@kompyDatabaseLogger'
            $dbPrefix: '%env(KOMPY_DB_PREFIX)%'


    doctrineDatabaseRoot:
        class: App\Shared\Infrastructure\Database\Database
        factory: ['@App\Shared\Infrastructure\Database\Factory\DatabaseDoctrine', 'create']

    doctrineDatabase:
        class: App\Shared\Infrastructure\Database\Decorator\DatabaseLoggerDecorator
        arguments:
            $database: '@doctrineDatabaseRoot'
            $databaseName: '%env(DOCTRINE_DB)%'
            $type: !php/const App\Shared\Infrastructure\Database\DatabaseType::MySQL


    pymLegacyDatabaseRoot:
        class: App\Shared\Infrastructure\Database\Database
        factory: [ '@App\Shared\Infrastructure\Database\Factory\DatabasePymLegacyFactory', 'create' ]

    pymLegacyDatabaseLogger:
        class: App\Shared\Infrastructure\Database\Decorator\DatabaseLoggerDecorator
        arguments:
            $database: '@pymLegacyDatabaseRoot'
            $databaseName: '%env(PYM_LEGACY_DB_NAME)%'
            $type: !php/const App\Shared\Infrastructure\Database\DatabaseType::MySQL

    pymLegacyDatabase:
        class: App\Shared\Infrastructure\Database\Decorator\DatabasePrefixerDecorator
        arguments:
            $database: '@pymLegacyDatabaseLogger'
            $dbPrefix: '%env(PYM_LEGACY_DB_PREFIX)%'


    App\Shared\Infrastructure\Database\DatabaseBus:
        arguments:
            - !tagged_iterator kpy.database_factory

    App\ShippingCostCalculator\Infrastructure\Persistence\Repository\RangeRepository:
        arguments:
            $aquaDatabase: '@aquaDatabase'

    mrw:
        class: App\ShippingCostCalculator\Domain\Carrier
        factory: ['@App\ShippingCostCalculator\Domain\Builder\CarrierBuilder', 'getMRW']

    # siempre que un servicio requiere la interfaz GooglePublicApiInterface se inyectará la clase GooglePublicApi
    App\Google\Infrastructure\API\GooglePublicApi: ~
    App\Google\Infrastructure\API\GooglePublicApiInterface: '@App\Google\Infrastructure\API\GooglePublicApi'
